6758881: (launcher) needs to throw NoClassDefFoundError instead of JavaRuntimeException
The launcher will throw the Error vs. Exception, also fixed some minor issues with the tests.

Reviewed-by: darcy